// Code generated by xorm reverse.
// 表结构函数
package dbmodel

import "fmt"
import "encoding/json"

func (tb *AccountUser) SubName() string {
	return "account_user"
}

func (tb *AccountUser) String() string {
	data, err := json.Marshal(tb)
	if err != nil {
		return fmt.Sprintf("%+v", tb)
	}
	return string(data)
}
