// Code generated by xorm reverse.
// 表结构函数
package dbmodel

import "encoding/json"

func (tb *AccountUser) SubName() string {
	return "account_user"
}

func (tb *Friends) SubName() string {
	return "friends"
}

func (tb *HistoryMessage) SubName() string {
	return "history_message"
}

func (tb *AccountUser) String() string {
	data, err := json.Marshal(tb)
	if err != nil {
		return err.Error()
	}
	return string(data)
}

func (tb *Friends) String() string {
	data, err := json.Marshal(tb)
	if err != nil {
		return err.Error()
	}
	return string(data)
}

func (tb *HistoryMessage) String() string {
	data, err := json.Marshal(tb)
	if err != nil {
		return err.Error()
	}
	return string(data)
}
