// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: home_message.proto

package im_home_proto

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type GetSingleChatHistoryReq struct {
	MaxNotGainMessageID int64 `protobuf:"varint,1,opt,name=MaxNotGainMessageID,proto3" json:"MaxNotGainMessageID,omitempty"`
	FriendID            int64 `protobuf:"varint,2,opt,name=FriendID,proto3" json:"FriendID,omitempty"`
}

func (m *GetSingleChatHistoryReq) Reset()         { *m = GetSingleChatHistoryReq{} }
func (m *GetSingleChatHistoryReq) String() string { return proto.CompactTextString(m) }
func (*GetSingleChatHistoryReq) ProtoMessage()    {}
func (*GetSingleChatHistoryReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e858025c0727086, []int{0}
}
func (m *GetSingleChatHistoryReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetSingleChatHistoryReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetSingleChatHistoryReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetSingleChatHistoryReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSingleChatHistoryReq.Merge(m, src)
}
func (m *GetSingleChatHistoryReq) XXX_Size() int {
	return m.Size()
}
func (m *GetSingleChatHistoryReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSingleChatHistoryReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetSingleChatHistoryReq proto.InternalMessageInfo

func (m *GetSingleChatHistoryReq) GetMaxNotGainMessageID() int64 {
	if m != nil {
		return m.MaxNotGainMessageID
	}
	return 0
}

func (m *GetSingleChatHistoryReq) GetFriendID() int64 {
	if m != nil {
		return m.FriendID
	}
	return 0
}

type GetSingleChatHistoryRes struct {
	FriendID int64          `protobuf:"varint,1,opt,name=FriendID,proto3" json:"FriendID,omitempty"`
	Data     []*ChatMessage `protobuf:"bytes,2,rep,name=Data,proto3" json:"Data,omitempty"`
}

func (m *GetSingleChatHistoryRes) Reset()         { *m = GetSingleChatHistoryRes{} }
func (m *GetSingleChatHistoryRes) String() string { return proto.CompactTextString(m) }
func (*GetSingleChatHistoryRes) ProtoMessage()    {}
func (*GetSingleChatHistoryRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e858025c0727086, []int{1}
}
func (m *GetSingleChatHistoryRes) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetSingleChatHistoryRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetSingleChatHistoryRes.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetSingleChatHistoryRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSingleChatHistoryRes.Merge(m, src)
}
func (m *GetSingleChatHistoryRes) XXX_Size() int {
	return m.Size()
}
func (m *GetSingleChatHistoryRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSingleChatHistoryRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetSingleChatHistoryRes proto.InternalMessageInfo

func (m *GetSingleChatHistoryRes) GetFriendID() int64 {
	if m != nil {
		return m.FriendID
	}
	return 0
}

func (m *GetSingleChatHistoryRes) GetData() []*ChatMessage {
	if m != nil {
		return m.Data
	}
	return nil
}

// 读取离线消息
type ReadOfflineMessageReq struct {
	FriendID int64 `protobuf:"varint,1,opt,name=FriendID,proto3" json:"FriendID,omitempty"`
}

func (m *ReadOfflineMessageReq) Reset()         { *m = ReadOfflineMessageReq{} }
func (m *ReadOfflineMessageReq) String() string { return proto.CompactTextString(m) }
func (*ReadOfflineMessageReq) ProtoMessage()    {}
func (*ReadOfflineMessageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e858025c0727086, []int{2}
}
func (m *ReadOfflineMessageReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ReadOfflineMessageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ReadOfflineMessageReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ReadOfflineMessageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadOfflineMessageReq.Merge(m, src)
}
func (m *ReadOfflineMessageReq) XXX_Size() int {
	return m.Size()
}
func (m *ReadOfflineMessageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadOfflineMessageReq.DiscardUnknown(m)
}

var xxx_messageInfo_ReadOfflineMessageReq proto.InternalMessageInfo

func (m *ReadOfflineMessageReq) GetFriendID() int64 {
	if m != nil {
		return m.FriendID
	}
	return 0
}

type ReadOfflineMessageRes struct {
	FriendID int64          `protobuf:"varint,1,opt,name=FriendID,proto3" json:"FriendID,omitempty"`
	Data     []*ChatMessage `protobuf:"bytes,2,rep,name=Data,proto3" json:"Data,omitempty"`
}

func (m *ReadOfflineMessageRes) Reset()         { *m = ReadOfflineMessageRes{} }
func (m *ReadOfflineMessageRes) String() string { return proto.CompactTextString(m) }
func (*ReadOfflineMessageRes) ProtoMessage()    {}
func (*ReadOfflineMessageRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e858025c0727086, []int{3}
}
func (m *ReadOfflineMessageRes) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ReadOfflineMessageRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ReadOfflineMessageRes.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ReadOfflineMessageRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadOfflineMessageRes.Merge(m, src)
}
func (m *ReadOfflineMessageRes) XXX_Size() int {
	return m.Size()
}
func (m *ReadOfflineMessageRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadOfflineMessageRes.DiscardUnknown(m)
}

var xxx_messageInfo_ReadOfflineMessageRes proto.InternalMessageInfo

func (m *ReadOfflineMessageRes) GetFriendID() int64 {
	if m != nil {
		return m.FriendID
	}
	return 0
}

func (m *ReadOfflineMessageRes) GetData() []*ChatMessage {
	if m != nil {
		return m.Data
	}
	return nil
}

// 下载文件消息(文件或者图片)
type DownLoadFileMessageReq struct {
	FriendID        int64                `protobuf:"varint,1,opt,name=FriendID,proto3" json:"FriendID,omitempty"`
	MessageID       int64                `protobuf:"varint,2,opt,name=MessageID,proto3" json:"MessageID,omitempty"`
	FileIndex       int32                `protobuf:"varint,3,opt,name=FileIndex,proto3" json:"FileIndex,omitempty"`
	MessageFileType MessageFileType_Enum `protobuf:"varint,4,opt,name=MessageFileType,proto3,enum=im_home_proto.MessageFileType_Enum" json:"MessageFileType,omitempty"`
}

func (m *DownLoadFileMessageReq) Reset()         { *m = DownLoadFileMessageReq{} }
func (m *DownLoadFileMessageReq) String() string { return proto.CompactTextString(m) }
func (*DownLoadFileMessageReq) ProtoMessage()    {}
func (*DownLoadFileMessageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e858025c0727086, []int{4}
}
func (m *DownLoadFileMessageReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DownLoadFileMessageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DownLoadFileMessageReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DownLoadFileMessageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownLoadFileMessageReq.Merge(m, src)
}
func (m *DownLoadFileMessageReq) XXX_Size() int {
	return m.Size()
}
func (m *DownLoadFileMessageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DownLoadFileMessageReq.DiscardUnknown(m)
}

var xxx_messageInfo_DownLoadFileMessageReq proto.InternalMessageInfo

func (m *DownLoadFileMessageReq) GetFriendID() int64 {
	if m != nil {
		return m.FriendID
	}
	return 0
}

func (m *DownLoadFileMessageReq) GetMessageID() int64 {
	if m != nil {
		return m.MessageID
	}
	return 0
}

func (m *DownLoadFileMessageReq) GetFileIndex() int32 {
	if m != nil {
		return m.FileIndex
	}
	return 0
}

func (m *DownLoadFileMessageReq) GetMessageFileType() MessageFileType_Enum {
	if m != nil {
		return m.MessageFileType
	}
	return MessageFileType_Enum_MessageFileType_Enum_Default
}

type DownLoadFileMessageRes struct {
	FriendID        int64                `protobuf:"varint,1,opt,name=FriendID,proto3" json:"FriendID,omitempty"`
	MessageID       int64                `protobuf:"varint,2,opt,name=MessageID,proto3" json:"MessageID,omitempty"`
	FileIndex       int32                `protobuf:"varint,3,opt,name=FileIndex,proto3" json:"FileIndex,omitempty"`
	FileData        string               `protobuf:"bytes,4,opt,name=FileData,proto3" json:"FileData,omitempty"`
	MessageFileType MessageFileType_Enum `protobuf:"varint,5,opt,name=MessageFileType,proto3,enum=im_home_proto.MessageFileType_Enum" json:"MessageFileType,omitempty"`
}

func (m *DownLoadFileMessageRes) Reset()         { *m = DownLoadFileMessageRes{} }
func (m *DownLoadFileMessageRes) String() string { return proto.CompactTextString(m) }
func (*DownLoadFileMessageRes) ProtoMessage()    {}
func (*DownLoadFileMessageRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e858025c0727086, []int{5}
}
func (m *DownLoadFileMessageRes) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DownLoadFileMessageRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DownLoadFileMessageRes.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DownLoadFileMessageRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownLoadFileMessageRes.Merge(m, src)
}
func (m *DownLoadFileMessageRes) XXX_Size() int {
	return m.Size()
}
func (m *DownLoadFileMessageRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DownLoadFileMessageRes.DiscardUnknown(m)
}

var xxx_messageInfo_DownLoadFileMessageRes proto.InternalMessageInfo

func (m *DownLoadFileMessageRes) GetFriendID() int64 {
	if m != nil {
		return m.FriendID
	}
	return 0
}

func (m *DownLoadFileMessageRes) GetMessageID() int64 {
	if m != nil {
		return m.MessageID
	}
	return 0
}

func (m *DownLoadFileMessageRes) GetFileIndex() int32 {
	if m != nil {
		return m.FileIndex
	}
	return 0
}

func (m *DownLoadFileMessageRes) GetFileData() string {
	if m != nil {
		return m.FileData
	}
	return ""
}

func (m *DownLoadFileMessageRes) GetMessageFileType() MessageFileType_Enum {
	if m != nil {
		return m.MessageFileType
	}
	return MessageFileType_Enum_MessageFileType_Enum_Default
}

func init() {
	proto.RegisterType((*GetSingleChatHistoryReq)(nil), "im_home_proto.GetSingleChatHistoryReq")
	proto.RegisterType((*GetSingleChatHistoryRes)(nil), "im_home_proto.GetSingleChatHistoryRes")
	proto.RegisterType((*ReadOfflineMessageReq)(nil), "im_home_proto.ReadOfflineMessageReq")
	proto.RegisterType((*ReadOfflineMessageRes)(nil), "im_home_proto.ReadOfflineMessageRes")
	proto.RegisterType((*DownLoadFileMessageReq)(nil), "im_home_proto.DownLoadFileMessageReq")
	proto.RegisterType((*DownLoadFileMessageRes)(nil), "im_home_proto.DownLoadFileMessageRes")
}

func init() { proto.RegisterFile("home_message.proto", fileDescriptor_6e858025c0727086) }

var fileDescriptor_6e858025c0727086 = []byte{
	// 384 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x50, 0xcd, 0xaa, 0xd3, 0x40,
	0x14, 0xee, 0xdc, 0xde, 0x2b, 0xde, 0x11, 0x2d, 0x44, 0xd4, 0x50, 0x24, 0x84, 0xb8, 0xc9, 0xa6,
	0x89, 0xb4, 0x6f, 0x50, 0x63, 0x6b, 0xc0, 0x28, 0xa4, 0xae, 0x44, 0x28, 0xd3, 0xe4, 0x34, 0x19,
	0xc8, 0xcc, 0xb4, 0x99, 0xa9, 0xb6, 0x6f, 0xe1, 0x1b, 0xb9, 0x75, 0xd9, 0xa5, 0xe0, 0x46, 0xda,
	0x17, 0x91, 0x4c, 0x6b, 0x4b, 0x4a, 0x2b, 0x22, 0xba, 0x9a, 0x39, 0x3f, 0xdf, 0xdf, 0xc1, 0x46,
	0x2e, 0x18, 0x8c, 0x19, 0x48, 0x49, 0x32, 0xf0, 0x66, 0xa5, 0x50, 0xc2, 0xb8, 0x4f, 0xd9, 0x58,
	0xb7, 0x75, 0xd9, 0x6e, 0xe9, 0x7f, 0x92, 0x13, 0xb5, 0x9b, 0x3b, 0x19, 0x7e, 0x32, 0x04, 0x35,
	0xa2, 0x3c, 0x2b, 0xe0, 0x45, 0x4e, 0xd4, 0x2b, 0x2a, 0x95, 0x28, 0x57, 0x31, 0xcc, 0x8d, 0xe7,
	0xf8, 0x61, 0x44, 0x96, 0x6f, 0x84, 0x1a, 0x12, 0xca, 0xa3, 0x1d, 0x6b, 0x18, 0x98, 0xc8, 0x46,
	0x6e, 0x33, 0x3e, 0x37, 0x32, 0xda, 0xf8, 0xee, 0xa0, 0xa4, 0xc0, 0xd3, 0x30, 0x30, 0xaf, 0xf4,
	0xda, 0xa1, 0x76, 0xe0, 0x92, 0x90, 0xac, 0xc1, 0x50, 0x1d, 0x66, 0x78, 0xf8, 0x3a, 0x20, 0x8a,
	0x98, 0x57, 0x76, 0xd3, 0xbd, 0xd7, 0x6d, 0x7b, 0xb5, 0x38, 0x5e, 0x45, 0xb4, 0x97, 0x8f, 0xf5,
	0x9e, 0xd3, 0xc3, 0x8f, 0x62, 0x20, 0xe9, 0xdb, 0xe9, 0xb4, 0xa0, 0x1c, 0x7e, 0xcd, 0x60, 0xfe,
	0x3b, 0x11, 0x27, 0x39, 0x0f, 0xfa, 0xb7, 0xce, 0xbe, 0x20, 0xfc, 0x38, 0x10, 0x9f, 0xf8, 0x6b,
	0x41, 0xd2, 0x01, 0x2d, 0xfe, 0xd0, 0x9b, 0xf1, 0x14, 0xdf, 0x1e, 0x6f, 0xbf, 0x3b, 0xea, 0xb1,
	0x51, 0x4d, 0x2b, 0xae, 0x90, 0xa7, 0xb0, 0x34, 0x9b, 0x36, 0x72, 0x6f, 0xe2, 0x63, 0xc3, 0x88,
	0x70, 0x6b, 0xbf, 0x5a, 0xf5, 0xde, 0xad, 0x66, 0x60, 0x5e, 0xdb, 0xc8, 0x7d, 0xd0, 0x7d, 0x76,
	0xe2, 0xf6, 0x64, 0x6b, 0xfc, 0x92, 0x2f, 0x58, 0x7c, 0x8a, 0x75, 0xbe, 0x5f, 0x4a, 0x20, 0xff,
	0x5b, 0x82, 0x8a, 0x97, 0x16, 0xa0, 0x0f, 0x5d, 0x59, 0xbf, 0x8d, 0x0f, 0xf5, 0xb9, 0x74, 0x37,
	0x7f, 0x9f, 0xae, 0xff, 0xe1, 0xeb, 0xc6, 0x42, 0xeb, 0x8d, 0x85, 0x7e, 0x6c, 0x2c, 0xf4, 0x79,
	0x6b, 0x35, 0xd6, 0x5b, 0xab, 0xf1, 0x6d, 0x6b, 0x35, 0xde, 0xf7, 0x33, 0xaa, 0xf2, 0xc5, 0xc4,
	0x4b, 0x04, 0xf3, 0x19, 0x65, 0x54, 0x76, 0xa4, 0x1f, 0x46, 0x9d, 0x11, 0x94, 0x1f, 0x69, 0x02,
	0xbe, 0x2c, 0x13, 0x3f, 0x11, 0x8c, 0x09, 0xbe, 0x7f, 0xb4, 0xaa, 0x5f, 0xf3, 0x30, 0xb9, 0xa3,
	0x9f, 0xde, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe7, 0x26, 0x4a, 0x76, 0xa4, 0x03, 0x00, 0x00,
}

func (m *GetSingleChatHistoryReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetSingleChatHistoryReq) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetSingleChatHistoryReq) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.FriendID != 0 {
		i = encodeVarintHomeMessage(dAtA, i, uint64(m.FriendID))
		i--
		dAtA[i] = 0x10
	}
	if m.MaxNotGainMessageID != 0 {
		i = encodeVarintHomeMessage(dAtA, i, uint64(m.MaxNotGainMessageID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *GetSingleChatHistoryRes) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetSingleChatHistoryRes) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetSingleChatHistoryRes) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Data) > 0 {
		for iNdEx := len(m.Data) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Data[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintHomeMessage(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.FriendID != 0 {
		i = encodeVarintHomeMessage(dAtA, i, uint64(m.FriendID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ReadOfflineMessageReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ReadOfflineMessageReq) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ReadOfflineMessageReq) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.FriendID != 0 {
		i = encodeVarintHomeMessage(dAtA, i, uint64(m.FriendID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ReadOfflineMessageRes) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ReadOfflineMessageRes) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ReadOfflineMessageRes) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Data) > 0 {
		for iNdEx := len(m.Data) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Data[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintHomeMessage(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.FriendID != 0 {
		i = encodeVarintHomeMessage(dAtA, i, uint64(m.FriendID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *DownLoadFileMessageReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DownLoadFileMessageReq) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DownLoadFileMessageReq) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MessageFileType != 0 {
		i = encodeVarintHomeMessage(dAtA, i, uint64(m.MessageFileType))
		i--
		dAtA[i] = 0x20
	}
	if m.FileIndex != 0 {
		i = encodeVarintHomeMessage(dAtA, i, uint64(m.FileIndex))
		i--
		dAtA[i] = 0x18
	}
	if m.MessageID != 0 {
		i = encodeVarintHomeMessage(dAtA, i, uint64(m.MessageID))
		i--
		dAtA[i] = 0x10
	}
	if m.FriendID != 0 {
		i = encodeVarintHomeMessage(dAtA, i, uint64(m.FriendID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *DownLoadFileMessageRes) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DownLoadFileMessageRes) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DownLoadFileMessageRes) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MessageFileType != 0 {
		i = encodeVarintHomeMessage(dAtA, i, uint64(m.MessageFileType))
		i--
		dAtA[i] = 0x28
	}
	if len(m.FileData) > 0 {
		i -= len(m.FileData)
		copy(dAtA[i:], m.FileData)
		i = encodeVarintHomeMessage(dAtA, i, uint64(len(m.FileData)))
		i--
		dAtA[i] = 0x22
	}
	if m.FileIndex != 0 {
		i = encodeVarintHomeMessage(dAtA, i, uint64(m.FileIndex))
		i--
		dAtA[i] = 0x18
	}
	if m.MessageID != 0 {
		i = encodeVarintHomeMessage(dAtA, i, uint64(m.MessageID))
		i--
		dAtA[i] = 0x10
	}
	if m.FriendID != 0 {
		i = encodeVarintHomeMessage(dAtA, i, uint64(m.FriendID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintHomeMessage(dAtA []byte, offset int, v uint64) int {
	offset -= sovHomeMessage(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GetSingleChatHistoryReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MaxNotGainMessageID != 0 {
		n += 1 + sovHomeMessage(uint64(m.MaxNotGainMessageID))
	}
	if m.FriendID != 0 {
		n += 1 + sovHomeMessage(uint64(m.FriendID))
	}
	return n
}

func (m *GetSingleChatHistoryRes) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.FriendID != 0 {
		n += 1 + sovHomeMessage(uint64(m.FriendID))
	}
	if len(m.Data) > 0 {
		for _, e := range m.Data {
			l = e.Size()
			n += 1 + l + sovHomeMessage(uint64(l))
		}
	}
	return n
}

func (m *ReadOfflineMessageReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.FriendID != 0 {
		n += 1 + sovHomeMessage(uint64(m.FriendID))
	}
	return n
}

func (m *ReadOfflineMessageRes) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.FriendID != 0 {
		n += 1 + sovHomeMessage(uint64(m.FriendID))
	}
	if len(m.Data) > 0 {
		for _, e := range m.Data {
			l = e.Size()
			n += 1 + l + sovHomeMessage(uint64(l))
		}
	}
	return n
}

func (m *DownLoadFileMessageReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.FriendID != 0 {
		n += 1 + sovHomeMessage(uint64(m.FriendID))
	}
	if m.MessageID != 0 {
		n += 1 + sovHomeMessage(uint64(m.MessageID))
	}
	if m.FileIndex != 0 {
		n += 1 + sovHomeMessage(uint64(m.FileIndex))
	}
	if m.MessageFileType != 0 {
		n += 1 + sovHomeMessage(uint64(m.MessageFileType))
	}
	return n
}

func (m *DownLoadFileMessageRes) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.FriendID != 0 {
		n += 1 + sovHomeMessage(uint64(m.FriendID))
	}
	if m.MessageID != 0 {
		n += 1 + sovHomeMessage(uint64(m.MessageID))
	}
	if m.FileIndex != 0 {
		n += 1 + sovHomeMessage(uint64(m.FileIndex))
	}
	l = len(m.FileData)
	if l > 0 {
		n += 1 + l + sovHomeMessage(uint64(l))
	}
	if m.MessageFileType != 0 {
		n += 1 + sovHomeMessage(uint64(m.MessageFileType))
	}
	return n
}

func sovHomeMessage(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozHomeMessage(x uint64) (n int) {
	return sovHomeMessage(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GetSingleChatHistoryReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHomeMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetSingleChatHistoryReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetSingleChatHistoryReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxNotGainMessageID", wireType)
			}
			m.MaxNotGainMessageID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHomeMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxNotGainMessageID |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FriendID", wireType)
			}
			m.FriendID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHomeMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FriendID |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipHomeMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthHomeMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetSingleChatHistoryRes) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHomeMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetSingleChatHistoryRes: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetSingleChatHistoryRes: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FriendID", wireType)
			}
			m.FriendID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHomeMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FriendID |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHomeMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthHomeMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthHomeMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data, &ChatMessage{})
			if err := m.Data[len(m.Data)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipHomeMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthHomeMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ReadOfflineMessageReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHomeMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ReadOfflineMessageReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ReadOfflineMessageReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FriendID", wireType)
			}
			m.FriendID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHomeMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FriendID |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipHomeMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthHomeMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ReadOfflineMessageRes) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHomeMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ReadOfflineMessageRes: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ReadOfflineMessageRes: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FriendID", wireType)
			}
			m.FriendID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHomeMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FriendID |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHomeMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthHomeMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthHomeMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data, &ChatMessage{})
			if err := m.Data[len(m.Data)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipHomeMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthHomeMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DownLoadFileMessageReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHomeMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DownLoadFileMessageReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DownLoadFileMessageReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FriendID", wireType)
			}
			m.FriendID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHomeMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FriendID |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessageID", wireType)
			}
			m.MessageID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHomeMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MessageID |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FileIndex", wireType)
			}
			m.FileIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHomeMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FileIndex |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessageFileType", wireType)
			}
			m.MessageFileType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHomeMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MessageFileType |= MessageFileType_Enum(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipHomeMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthHomeMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DownLoadFileMessageRes) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHomeMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DownLoadFileMessageRes: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DownLoadFileMessageRes: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FriendID", wireType)
			}
			m.FriendID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHomeMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FriendID |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessageID", wireType)
			}
			m.MessageID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHomeMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MessageID |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FileIndex", wireType)
			}
			m.FileIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHomeMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FileIndex |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FileData", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHomeMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHomeMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthHomeMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FileData = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessageFileType", wireType)
			}
			m.MessageFileType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHomeMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MessageFileType |= MessageFileType_Enum(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipHomeMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthHomeMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipHomeMessage(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowHomeMessage
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowHomeMessage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowHomeMessage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthHomeMessage
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupHomeMessage
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthHomeMessage
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthHomeMessage        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowHomeMessage          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupHomeMessage = fmt.Errorf("proto: unexpected end of group")
)
