// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: home_friends.proto

package im_home_proto

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// 获取好友列表
type GetFriendsListReq struct {
}

func (m *GetFriendsListReq) Reset()         { *m = GetFriendsListReq{} }
func (m *GetFriendsListReq) String() string { return proto.CompactTextString(m) }
func (*GetFriendsListReq) ProtoMessage()    {}
func (*GetFriendsListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_59b581ecf1919eda, []int{0}
}
func (m *GetFriendsListReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetFriendsListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetFriendsListReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetFriendsListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFriendsListReq.Merge(m, src)
}
func (m *GetFriendsListReq) XXX_Size() int {
	return m.Size()
}
func (m *GetFriendsListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFriendsListReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetFriendsListReq proto.InternalMessageInfo

type GetFriendsListRes struct {
	List []*GetFriendsListRes_BriedFriends `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
}

func (m *GetFriendsListRes) Reset()         { *m = GetFriendsListRes{} }
func (m *GetFriendsListRes) String() string { return proto.CompactTextString(m) }
func (*GetFriendsListRes) ProtoMessage()    {}
func (*GetFriendsListRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_59b581ecf1919eda, []int{1}
}
func (m *GetFriendsListRes) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetFriendsListRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetFriendsListRes.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetFriendsListRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFriendsListRes.Merge(m, src)
}
func (m *GetFriendsListRes) XXX_Size() int {
	return m.Size()
}
func (m *GetFriendsListRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFriendsListRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetFriendsListRes proto.InternalMessageInfo

func (m *GetFriendsListRes) GetList() []*GetFriendsListRes_BriedFriends {
	if m != nil {
		return m.List
	}
	return nil
}

type GetFriendsListRes_BriedFriends struct {
	// 好友简要信息
	UserID   int64  `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	UserName string `protobuf:"bytes,2,opt,name=UserName,proto3" json:"UserName,omitempty"`
	BOnline  bool   `protobuf:"varint,3,opt,name=bOnline,proto3" json:"bOnline,omitempty"`
}

func (m *GetFriendsListRes_BriedFriends) Reset()         { *m = GetFriendsListRes_BriedFriends{} }
func (m *GetFriendsListRes_BriedFriends) String() string { return proto.CompactTextString(m) }
func (*GetFriendsListRes_BriedFriends) ProtoMessage()    {}
func (*GetFriendsListRes_BriedFriends) Descriptor() ([]byte, []int) {
	return fileDescriptor_59b581ecf1919eda, []int{1, 0}
}
func (m *GetFriendsListRes_BriedFriends) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetFriendsListRes_BriedFriends) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetFriendsListRes_BriedFriends.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetFriendsListRes_BriedFriends) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFriendsListRes_BriedFriends.Merge(m, src)
}
func (m *GetFriendsListRes_BriedFriends) XXX_Size() int {
	return m.Size()
}
func (m *GetFriendsListRes_BriedFriends) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFriendsListRes_BriedFriends.DiscardUnknown(m)
}

var xxx_messageInfo_GetFriendsListRes_BriedFriends proto.InternalMessageInfo

func (m *GetFriendsListRes_BriedFriends) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *GetFriendsListRes_BriedFriends) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *GetFriendsListRes_BriedFriends) GetBOnline() bool {
	if m != nil {
		return m.BOnline
	}
	return false
}

// 添加好友
type ApplyFriendsReq struct {
	ApplyFriendsID int64 `protobuf:"varint,1,opt,name=ApplyFriendsID,proto3" json:"ApplyFriendsID,omitempty"`
}

func (m *ApplyFriendsReq) Reset()         { *m = ApplyFriendsReq{} }
func (m *ApplyFriendsReq) String() string { return proto.CompactTextString(m) }
func (*ApplyFriendsReq) ProtoMessage()    {}
func (*ApplyFriendsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_59b581ecf1919eda, []int{2}
}
func (m *ApplyFriendsReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ApplyFriendsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ApplyFriendsReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ApplyFriendsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyFriendsReq.Merge(m, src)
}
func (m *ApplyFriendsReq) XXX_Size() int {
	return m.Size()
}
func (m *ApplyFriendsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyFriendsReq.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyFriendsReq proto.InternalMessageInfo

func (m *ApplyFriendsReq) GetApplyFriendsID() int64 {
	if m != nil {
		return m.ApplyFriendsID
	}
	return 0
}

type ApplyFriendsRes struct {
	ApplyFriendsID int64 `protobuf:"varint,1,opt,name=ApplyFriendsID,proto3" json:"ApplyFriendsID,omitempty"`
}

func (m *ApplyFriendsRes) Reset()         { *m = ApplyFriendsRes{} }
func (m *ApplyFriendsRes) String() string { return proto.CompactTextString(m) }
func (*ApplyFriendsRes) ProtoMessage()    {}
func (*ApplyFriendsRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_59b581ecf1919eda, []int{3}
}
func (m *ApplyFriendsRes) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ApplyFriendsRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ApplyFriendsRes.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ApplyFriendsRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyFriendsRes.Merge(m, src)
}
func (m *ApplyFriendsRes) XXX_Size() int {
	return m.Size()
}
func (m *ApplyFriendsRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyFriendsRes.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyFriendsRes proto.InternalMessageInfo

func (m *ApplyFriendsRes) GetApplyFriendsID() int64 {
	if m != nil {
		return m.ApplyFriendsID
	}
	return 0
}

// 同意好友申请
type AgreeFriendApplyReq struct {
	FriendsID int64 `protobuf:"varint,1,opt,name=FriendsID,proto3" json:"FriendsID,omitempty"`
}

func (m *AgreeFriendApplyReq) Reset()         { *m = AgreeFriendApplyReq{} }
func (m *AgreeFriendApplyReq) String() string { return proto.CompactTextString(m) }
func (*AgreeFriendApplyReq) ProtoMessage()    {}
func (*AgreeFriendApplyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_59b581ecf1919eda, []int{4}
}
func (m *AgreeFriendApplyReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AgreeFriendApplyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AgreeFriendApplyReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AgreeFriendApplyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgreeFriendApplyReq.Merge(m, src)
}
func (m *AgreeFriendApplyReq) XXX_Size() int {
	return m.Size()
}
func (m *AgreeFriendApplyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AgreeFriendApplyReq.DiscardUnknown(m)
}

var xxx_messageInfo_AgreeFriendApplyReq proto.InternalMessageInfo

func (m *AgreeFriendApplyReq) GetFriendsID() int64 {
	if m != nil {
		return m.FriendsID
	}
	return 0
}

type AgreeFriendApplyRes struct {
	FriendsID int64 `protobuf:"varint,1,opt,name=FriendsID,proto3" json:"FriendsID,omitempty"`
}

func (m *AgreeFriendApplyRes) Reset()         { *m = AgreeFriendApplyRes{} }
func (m *AgreeFriendApplyRes) String() string { return proto.CompactTextString(m) }
func (*AgreeFriendApplyRes) ProtoMessage()    {}
func (*AgreeFriendApplyRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_59b581ecf1919eda, []int{5}
}
func (m *AgreeFriendApplyRes) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AgreeFriendApplyRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AgreeFriendApplyRes.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AgreeFriendApplyRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgreeFriendApplyRes.Merge(m, src)
}
func (m *AgreeFriendApplyRes) XXX_Size() int {
	return m.Size()
}
func (m *AgreeFriendApplyRes) XXX_DiscardUnknown() {
	xxx_messageInfo_AgreeFriendApplyRes.DiscardUnknown(m)
}

var xxx_messageInfo_AgreeFriendApplyRes proto.InternalMessageInfo

func (m *AgreeFriendApplyRes) GetFriendsID() int64 {
	if m != nil {
		return m.FriendsID
	}
	return 0
}

// 删除好友
type DelFriendsReq struct {
	FriendsID int64 `protobuf:"varint,1,opt,name=FriendsID,proto3" json:"FriendsID,omitempty"`
}

func (m *DelFriendsReq) Reset()         { *m = DelFriendsReq{} }
func (m *DelFriendsReq) String() string { return proto.CompactTextString(m) }
func (*DelFriendsReq) ProtoMessage()    {}
func (*DelFriendsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_59b581ecf1919eda, []int{6}
}
func (m *DelFriendsReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DelFriendsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DelFriendsReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DelFriendsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelFriendsReq.Merge(m, src)
}
func (m *DelFriendsReq) XXX_Size() int {
	return m.Size()
}
func (m *DelFriendsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DelFriendsReq.DiscardUnknown(m)
}

var xxx_messageInfo_DelFriendsReq proto.InternalMessageInfo

func (m *DelFriendsReq) GetFriendsID() int64 {
	if m != nil {
		return m.FriendsID
	}
	return 0
}

type DelFriendsRes struct {
	FriendsID int64 `protobuf:"varint,1,opt,name=FriendsID,proto3" json:"FriendsID,omitempty"`
}

func (m *DelFriendsRes) Reset()         { *m = DelFriendsRes{} }
func (m *DelFriendsRes) String() string { return proto.CompactTextString(m) }
func (*DelFriendsRes) ProtoMessage()    {}
func (*DelFriendsRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_59b581ecf1919eda, []int{7}
}
func (m *DelFriendsRes) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DelFriendsRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DelFriendsRes.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DelFriendsRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelFriendsRes.Merge(m, src)
}
func (m *DelFriendsRes) XXX_Size() int {
	return m.Size()
}
func (m *DelFriendsRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DelFriendsRes.DiscardUnknown(m)
}

var xxx_messageInfo_DelFriendsRes proto.InternalMessageInfo

func (m *DelFriendsRes) GetFriendsID() int64 {
	if m != nil {
		return m.FriendsID
	}
	return 0
}

func init() {
	proto.RegisterType((*GetFriendsListReq)(nil), "im_home_proto.GetFriendsListReq")
	proto.RegisterType((*GetFriendsListRes)(nil), "im_home_proto.GetFriendsListRes")
	proto.RegisterType((*GetFriendsListRes_BriedFriends)(nil), "im_home_proto.GetFriendsListRes.BriedFriends")
	proto.RegisterType((*ApplyFriendsReq)(nil), "im_home_proto.ApplyFriendsReq")
	proto.RegisterType((*ApplyFriendsRes)(nil), "im_home_proto.ApplyFriendsRes")
	proto.RegisterType((*AgreeFriendApplyReq)(nil), "im_home_proto.AgreeFriendApplyReq")
	proto.RegisterType((*AgreeFriendApplyRes)(nil), "im_home_proto.AgreeFriendApplyRes")
	proto.RegisterType((*DelFriendsReq)(nil), "im_home_proto.DelFriendsReq")
	proto.RegisterType((*DelFriendsRes)(nil), "im_home_proto.DelFriendsRes")
}

func init() { proto.RegisterFile("home_friends.proto", fileDescriptor_59b581ecf1919eda) }

var fileDescriptor_59b581ecf1919eda = []byte{
	// 319 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xca, 0xc8, 0xcf, 0x4d,
	0x8d, 0x4f, 0x2b, 0xca, 0x4c, 0xcd, 0x4b, 0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2,
	0xcd, 0xcc, 0x8d, 0x07, 0x0b, 0x83, 0xb9, 0x4a, 0xc2, 0x5c, 0x82, 0xee, 0xa9, 0x25, 0x6e, 0x10,
	0x25, 0x3e, 0x99, 0xc5, 0x25, 0x41, 0xa9, 0x85, 0x4a, 0x5b, 0x18, 0x31, 0x45, 0x8b, 0x85, 0x1c,
	0xb9, 0x58, 0x40, 0x4c, 0x09, 0x46, 0x05, 0x66, 0x0d, 0x6e, 0x23, 0x5d, 0x3d, 0x14, 0x83, 0xf4,
	0x30, 0xd4, 0xeb, 0x39, 0x15, 0x65, 0xa6, 0xa6, 0x40, 0xc5, 0x82, 0xc0, 0x5a, 0xa5, 0x62, 0xb8,
	0x78, 0x90, 0x45, 0x85, 0xc4, 0xb8, 0xd8, 0x42, 0x8b, 0x53, 0x8b, 0x3c, 0x5d, 0x24, 0x18, 0x15,
	0x18, 0x35, 0x98, 0x83, 0xa0, 0x3c, 0x21, 0x29, 0x2e, 0x0e, 0x10, 0xcb, 0x2f, 0x31, 0x37, 0x55,
	0x82, 0x49, 0x81, 0x51, 0x83, 0x33, 0x08, 0xce, 0x17, 0x92, 0xe0, 0x62, 0x4f, 0xf2, 0xcf, 0xcb,
	0xc9, 0xcc, 0x4b, 0x95, 0x60, 0x56, 0x60, 0xd4, 0xe0, 0x08, 0x82, 0x71, 0x95, 0x2c, 0xb9, 0xf8,
	0x1d, 0x0b, 0x0a, 0x72, 0x2a, 0x61, 0x76, 0xa6, 0x16, 0x0a, 0xa9, 0x71, 0xf1, 0x21, 0x0b, 0xc1,
	0x2d, 0x42, 0x13, 0xc5, 0xd4, 0x5a, 0x4c, 0xb4, 0x56, 0x63, 0x2e, 0x61, 0xc7, 0xf4, 0xa2, 0xd4,
	0x54, 0x88, 0x08, 0x58, 0x12, 0x64, 0xb3, 0x0c, 0x17, 0x27, 0xba, 0x4e, 0x4e, 0x02, 0x9a, 0x8a,
	0x09, 0x68, 0xd2, 0xe5, 0xe2, 0x75, 0x49, 0xcd, 0x41, 0xf2, 0x1d, 0x49, 0xca, 0x09, 0x98, 0xee,
	0x14, 0x73, 0xe2, 0x91, 0x1c, 0xe3, 0x85, 0x47, 0x72, 0x8c, 0x0f, 0x1e, 0xc9, 0x31, 0x4e, 0x78,
	0x2c, 0xc7, 0x70, 0xe1, 0xb1, 0x1c, 0xc3, 0x8d, 0xc7, 0x72, 0x0c, 0x51, 0x4e, 0xe9, 0x99, 0x25,
	0x19, 0xa5, 0x49, 0x7a, 0xc9, 0xf9, 0xb9, 0xfa, 0xb9, 0x99, 0xb9, 0x99, 0xc5, 0xba, 0xc5, 0xfa,
	0x9e, 0xbe, 0xba, 0xc1, 0xa9, 0x45, 0x65, 0x99, 0xc9, 0xa9, 0xfa, 0xc5, 0x45, 0xc9, 0xfa, 0xc9,
	0xf9, 0xb9, 0xb9, 0xf9, 0x79, 0x50, 0x0a, 0x9c, 0x20, 0xf4, 0x51, 0x92, 0x47, 0x12, 0x1b, 0x98,
	0x32, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x78, 0x81, 0xfb, 0x53, 0x93, 0x02, 0x00, 0x00,
}

func (m *GetFriendsListReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetFriendsListReq) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetFriendsListReq) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *GetFriendsListRes) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetFriendsListRes) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetFriendsListRes) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.List) > 0 {
		for iNdEx := len(m.List) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.List[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintHomeFriends(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *GetFriendsListRes_BriedFriends) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetFriendsListRes_BriedFriends) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetFriendsListRes_BriedFriends) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BOnline {
		i--
		if m.BOnline {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if len(m.UserName) > 0 {
		i -= len(m.UserName)
		copy(dAtA[i:], m.UserName)
		i = encodeVarintHomeFriends(dAtA, i, uint64(len(m.UserName)))
		i--
		dAtA[i] = 0x12
	}
	if m.UserID != 0 {
		i = encodeVarintHomeFriends(dAtA, i, uint64(m.UserID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ApplyFriendsReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ApplyFriendsReq) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ApplyFriendsReq) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ApplyFriendsID != 0 {
		i = encodeVarintHomeFriends(dAtA, i, uint64(m.ApplyFriendsID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ApplyFriendsRes) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ApplyFriendsRes) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ApplyFriendsRes) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ApplyFriendsID != 0 {
		i = encodeVarintHomeFriends(dAtA, i, uint64(m.ApplyFriendsID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *AgreeFriendApplyReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AgreeFriendApplyReq) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AgreeFriendApplyReq) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.FriendsID != 0 {
		i = encodeVarintHomeFriends(dAtA, i, uint64(m.FriendsID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *AgreeFriendApplyRes) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AgreeFriendApplyRes) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AgreeFriendApplyRes) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.FriendsID != 0 {
		i = encodeVarintHomeFriends(dAtA, i, uint64(m.FriendsID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *DelFriendsReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DelFriendsReq) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DelFriendsReq) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.FriendsID != 0 {
		i = encodeVarintHomeFriends(dAtA, i, uint64(m.FriendsID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *DelFriendsRes) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DelFriendsRes) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DelFriendsRes) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.FriendsID != 0 {
		i = encodeVarintHomeFriends(dAtA, i, uint64(m.FriendsID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintHomeFriends(dAtA []byte, offset int, v uint64) int {
	offset -= sovHomeFriends(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GetFriendsListReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *GetFriendsListRes) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.List) > 0 {
		for _, e := range m.List {
			l = e.Size()
			n += 1 + l + sovHomeFriends(uint64(l))
		}
	}
	return n
}

func (m *GetFriendsListRes_BriedFriends) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.UserID != 0 {
		n += 1 + sovHomeFriends(uint64(m.UserID))
	}
	l = len(m.UserName)
	if l > 0 {
		n += 1 + l + sovHomeFriends(uint64(l))
	}
	if m.BOnline {
		n += 2
	}
	return n
}

func (m *ApplyFriendsReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ApplyFriendsID != 0 {
		n += 1 + sovHomeFriends(uint64(m.ApplyFriendsID))
	}
	return n
}

func (m *ApplyFriendsRes) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ApplyFriendsID != 0 {
		n += 1 + sovHomeFriends(uint64(m.ApplyFriendsID))
	}
	return n
}

func (m *AgreeFriendApplyReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.FriendsID != 0 {
		n += 1 + sovHomeFriends(uint64(m.FriendsID))
	}
	return n
}

func (m *AgreeFriendApplyRes) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.FriendsID != 0 {
		n += 1 + sovHomeFriends(uint64(m.FriendsID))
	}
	return n
}

func (m *DelFriendsReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.FriendsID != 0 {
		n += 1 + sovHomeFriends(uint64(m.FriendsID))
	}
	return n
}

func (m *DelFriendsRes) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.FriendsID != 0 {
		n += 1 + sovHomeFriends(uint64(m.FriendsID))
	}
	return n
}

func sovHomeFriends(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozHomeFriends(x uint64) (n int) {
	return sovHomeFriends(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GetFriendsListReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHomeFriends
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetFriendsListReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetFriendsListReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipHomeFriends(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthHomeFriends
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetFriendsListRes) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHomeFriends
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetFriendsListRes: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetFriendsListRes: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field List", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHomeFriends
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthHomeFriends
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthHomeFriends
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.List = append(m.List, &GetFriendsListRes_BriedFriends{})
			if err := m.List[len(m.List)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipHomeFriends(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthHomeFriends
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetFriendsListRes_BriedFriends) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHomeFriends
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BriedFriends: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BriedFriends: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserID", wireType)
			}
			m.UserID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHomeFriends
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UserID |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHomeFriends
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHomeFriends
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthHomeFriends
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BOnline", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHomeFriends
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.BOnline = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipHomeFriends(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthHomeFriends
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ApplyFriendsReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHomeFriends
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ApplyFriendsReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ApplyFriendsReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApplyFriendsID", wireType)
			}
			m.ApplyFriendsID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHomeFriends
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ApplyFriendsID |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipHomeFriends(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthHomeFriends
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ApplyFriendsRes) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHomeFriends
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ApplyFriendsRes: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ApplyFriendsRes: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApplyFriendsID", wireType)
			}
			m.ApplyFriendsID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHomeFriends
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ApplyFriendsID |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipHomeFriends(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthHomeFriends
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AgreeFriendApplyReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHomeFriends
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AgreeFriendApplyReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AgreeFriendApplyReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FriendsID", wireType)
			}
			m.FriendsID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHomeFriends
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FriendsID |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipHomeFriends(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthHomeFriends
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AgreeFriendApplyRes) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHomeFriends
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AgreeFriendApplyRes: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AgreeFriendApplyRes: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FriendsID", wireType)
			}
			m.FriendsID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHomeFriends
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FriendsID |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipHomeFriends(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthHomeFriends
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DelFriendsReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHomeFriends
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DelFriendsReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DelFriendsReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FriendsID", wireType)
			}
			m.FriendsID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHomeFriends
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FriendsID |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipHomeFriends(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthHomeFriends
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DelFriendsRes) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHomeFriends
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DelFriendsRes: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DelFriendsRes: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FriendsID", wireType)
			}
			m.FriendsID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHomeFriends
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FriendsID |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipHomeFriends(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthHomeFriends
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipHomeFriends(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowHomeFriends
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowHomeFriends
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowHomeFriends
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthHomeFriends
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupHomeFriends
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthHomeFriends
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthHomeFriends        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowHomeFriends          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupHomeFriends = fmt.Errorf("proto: unexpected end of group")
)
